services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=etl_user
      - POSTGRES_PASSWORD=DfIsTheBest
      - POSTGRES_DB=car_sales
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  etl:
    build:
      context: .
      dockerfile: Dockerfile.etl
    environment:
        - DATABASE_URL=postgresql://etl_user:DfIsTheBest@db:5432/car_sales
    command: ["python", "scripts/run_etl.py"]
    depends_on:
      db:
        condition: service_healthy

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    environment:
        - DATABASE_URL=postgresql://etl_user:DfIsTheBest@db:5432/car_sales
    command: ["streamlit", "run", "app/streamlit_app.py", "--server.port=8501"]
    ports:
      - "8501:8501"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
